name: Download GitHub Linguist

on:
  workflow_dispatch

jobs:
  download-linguist:
    permissions:
      contents: read
      packages: read
      id-token: write
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/expert-services/linguist@sha256:4782256bbb1d07eee167d2abf2b0bf4329d1e84efc4c4af83ff114f762d0e5c0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: github-linguist
        run: |
          pwd
          ls -al
          whoami
          chown -R $USER:$USER $GITHUB_WORKSPACE
          github-linguist --breakdown --json 
          
