name: Download GitHub Linguist

on:
  workflow_dispatch

jobs:
  download-linguist:
    permissions:
      contents: read
      packages: read
      id-token: write
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/expert-services/linguist@sha256:1962a97d7d59c1b914eb5bcb17fa35cb13019a383e2df5df98cd3e31f28c6130
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: github-linguist
        run: |
          pwd
          ls -al
          git init 2> /dev/null > /dev/null
          git add --all 2> /dev/null > /dev/null
          git commit -m "local linguist auto commit" 2> /dev/null > /dev/null
          echo "created local git environment"
          github-linguist --breakdown --json "$@"
          rm -Rf .git 2> /dev/null > /dev/null
          
