name: Download GitHub Linguist

on:
  workflow_dispatch

jobs:
  download-linguist:
    permissions:
      contents: read
      packages: read
      id-token: write
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/expert-services/linguist@latest
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: github-linguist
        run: |
          chown -R root:root .
          github-linguist --json 
          
