name: Download GitHub Linguist

on:
  workflow_dispatch

jobs:
  download-linguist:
    permissions:
      contents: read
      packages: read
      id-token: write
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/expert-services/linguist@sha256:1962a97d7d59c1b914eb5bcb17fa35cb13019a383e2df5df98cd3e31f28c6130
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: github-linguist
        run: |
          pwd
          ls -al
          if git status 2> /dev/null > /dev/null; then
            echo "!!! This directory is already a git repository... please use the 'github-linguist' command instead"
            echo "!!! If this command exits unclean it will leave a git repository behind"
            echo "!!! You can remove the git repository by running 'rm -Rf .git'"
          else
            git init 2> /dev/null > /dev/null
            git add --all 2> /dev/null > /dev/null
            git commit -m "local linguist auto commit" 2> /dev/null > /dev/null
            linguist "$@"
            rm -Rf .git 2> /dev/null > /dev/null
          fi
          github-linguist
